import { mkdirSync, readdirSync, rmSync } from "node:fs";
import { basename, join } from "node:path";
import { and, asc, eq, inArray, isNull } from "drizzle-orm";
import type { Upload } from "./contracts";
import type { Db } from "./db";
import { schema } from "./db";
import type { UploadRow } from "./db/schema";
import { stateDir } from "./xdg";

// Message file attachments (browser upload / clipboard paste).
//
// A file is written ONCE at upload time (see the uploads route) to two places,
// both streamed so a large file never sits fully in memory:
//   - the host, under stateDir()/uploads/<instanceId>/<id>/<name>, the source
//     of truth backing the web preview and the user-facing download; and
//   - into the instance's running VM at GUEST_UPLOADS_DIR/<id>/<name>, so the
//     agent can read it by a stable absolute path.
// The VM copy is written by piping the bytes into a shell running AS THE AGENT
// USER (not root), so the files are agent-owned. That also means no bind mount
// (which can't cross the nested-isolade boundary) and no sandbox-service
// change. It lands on the VM's persistent overlay, so it survives restarts.
// There is no per-turn copy.
//
// The DB `uploads` table holds the metadata (see db/schema.ts). This module
// owns only the on-disk layout.

// Guest dir for uploads. Under /var/tmp because it's world-writable (mode 1777)
// so the agent user can create it, AND disk-backed (unlike /tmp, which is a
// tmpfs), so uploads survive VM restarts. Outside /workspace so they never show
// up in git status or the diff stats.
export const GUEST_UPLOADS_DIR = "/var/tmp/isolade/uploads";

/** Per-instance host dir holding the source-of-truth copies. */
export function uploadsInstanceDir(instanceId: string): string {
  return join(stateDir(), "uploads", instanceId);
}

// Keep the original filename (the model benefits from a real name) but strip
// any directory component so a crafted name can't escape the upload's own
// subdir. Fall back to a generic name when nothing usable is left.
export function safeFilename(filename: string): string {
  const base = basename(filename).replace(/^\.+/, "").trim();
  return base.length > 0 ? base : "file";
}

/** Host dir holding one upload's bytes. Created (recursively) so the route can
 * stream the request body straight into `<dir>/<name>`. */
export function ensureHostUploadDir(instanceId: string, id: string): string {
  const dir = join(uploadsInstanceDir(instanceId), id);
  mkdirSync(dir, { recursive: true });
  return dir;
}

/** Host path to a stored upload's bytes (download / preview / delete). */
export function uploadHostPath(instanceId: string, id: string, filename: string): string {
  return join(uploadsInstanceDir(instanceId), id, safeFilename(filename));
}

/** The per-upload dir inside the guest (parent of the bytes). `id` is a uuid,
 * so this is safe to interpolate into a shell command, but the route quotes it
 * anyway. */
export function guestUploadDir(id: string): string {
  return `${GUEST_UPLOADS_DIR}/${id}`;
}

/** Absolute path the agent sees inside the VM. Cited in the outgoing user
 * message so both providers can read it (Claude `Read`, codex `view_image` /
 * shell). Absolute so it's unambiguous across a multi-repo workspace. */
export function uploadGuestPath(id: string, filename: string): string {
  return `${guestUploadDir(id)}/${safeFilename(filename)}`;
}

/** Drop an instance's whole uploads dir when the instance is removed. */
export function removeUploadsForInstance(instanceId: string): void {
  rmSync(uploadsInstanceDir(instanceId), { recursive: true, force: true });
}

/** Drop one upload's bytes. Every row owns its own directory, so this takes the
 * whole thing rather than the file inside it. */
export function removeUploadDir(instanceId: string, id: string): void {
  rmSync(join(uploadsInstanceDir(instanceId), id), { recursive: true, force: true });
}

/** The wire view of an upload row (drops the internal association columns). */
export function toUpload(row: UploadRow): Upload {
  return { id: row.id, filename: row.filename, mediaType: row.mediaType, size: row.size };
}

// DB-backed store for upload metadata. Filesystem layout lives in the free
// functions above; this owns the `uploads` table.
//
// The table holds both directions (see db/schema.ts). Everything below that
// speaks of "a message's attachments" means the user's own, so it filters on
// origin: an assistant's inline images reach the client as render chunks, and
// must never appear in the attachment strip or be reusable as a browser upload.
export class UploadStore {
  constructor(private readonly db: Db) {}

  // Record the metadata row for an upload whose bytes the route has already
  // streamed to disk (and into the VM). messageId is null until the upload is
  // attached to a sent message. `id` and `filename` are the same ones used for
  // the on-disk paths, so they must already be sanitized/generated by the route.
  record(opts: {
    id: string;
    instanceId: string;
    filename: string;
    mediaType: string;
    size: number;
  }): Upload {
    this.db
      .insert(schema.uploads)
      .values({
        id: opts.id,
        instanceId: opts.instanceId,
        chatId: null,
        messageId: null,
        filename: opts.filename,
        mediaType: opts.mediaType,
        size: opts.size,
      })
      .run();
    return { id: opts.id, filename: opts.filename, mediaType: opts.mediaType, size: opts.size };
  }

  get(id: string): UploadRow | undefined {
    return this.db.select().from(schema.uploads).where(eq(schema.uploads.id, id)).get();
  }

  // Associate uploads with a sent message. A staged upload is claimed by this
  // chat on first use. An upload already claimed by the same chat may be reused
  // by an edited message version, while cross-instance and cross-chat ids are
  // ignored. The junction keeps the original message's association intact.
  // Returns the attached rows in caller-provided order.
  attach(instanceId: string, chatId: string, messageId: string, ids: string[]): UploadRow[] {
    const uniqueIds = [...new Set(ids)];
    if (uniqueIds.length === 0) return [];

    const candidates = this.db
      .select()
      .from(schema.uploads)
      .where(
        and(
          eq(schema.uploads.instanceId, instanceId),
          eq(schema.uploads.origin, "user"),
          inArray(schema.uploads.id, uniqueIds),
        ),
      )
      .all();
    const allowed = candidates.filter((row) => row.messageId === null || row.chatId === chatId);
    if (allowed.length === 0) return [];
    const allowedIds = allowed.map((row) => row.id);

    // First use claims the upload for this chat. These columns remain the
    // first-claim marker even when later message versions reuse the upload.
    this.db
      .update(schema.uploads)
      .set({ chatId, messageId })
      .where(
        and(
          eq(schema.uploads.instanceId, instanceId),
          inArray(schema.uploads.id, allowedIds),
          isNull(schema.uploads.messageId),
        ),
      )
      .run();

    this.db
      .insert(schema.messageUploads)
      .values(
        uniqueIds
          .filter((id) => allowedIds.includes(id))
          .map((uploadId, position) => ({ chatId, messageId, uploadId, position })),
      )
      .onConflictDoNothing()
      .run();

    const byId = new Map(allowed.map((row) => [row.id, row]));
    return uniqueIds.map((id) => byId.get(id)).filter((row): row is UploadRow => row !== undefined);
  }

  // Uploads for every message of a chat, grouped by messageId, so a transcript
  // fetch can decorate its messages in one query instead of N.
  byMessageForChat(chatId: string, messageIds?: string[]): Map<string, Upload[]> {
    if (messageIds?.length === 0) return new Map();
    const rows = this.db
      .select({ association: schema.messageUploads, upload: schema.uploads })
      .from(schema.messageUploads)
      .innerJoin(schema.uploads, eq(schema.messageUploads.uploadId, schema.uploads.id))
      .where(
        and(
          eq(schema.uploads.origin, "user"),
          messageIds
            ? and(
                eq(schema.messageUploads.chatId, chatId),
                inArray(schema.messageUploads.messageId, messageIds),
              )
            : eq(schema.messageUploads.chatId, chatId),
        ),
      )
      .orderBy(asc(schema.messageUploads.position))
      .all();
    const map = new Map<string, Upload[]>();
    for (const { association, upload } of rows) {
      const list = map.get(association.messageId) ?? [];
      list.push(toUpload(upload));
      map.set(association.messageId, list);
    }
    return map;
  }

  listForMessage(messageId: string): Upload[] {
    return this.db
      .select({ upload: schema.uploads })
      .from(schema.messageUploads)
      .innerJoin(schema.uploads, eq(schema.messageUploads.uploadId, schema.uploads.id))
      .where(and(eq(schema.messageUploads.messageId, messageId), eq(schema.uploads.origin, "user")))
      .orderBy(asc(schema.messageUploads.position))
      .all()
      .map(({ upload }) => toUpload(upload));
  }

  // ---- Assistant inline images (see agent-images.ts) ----

  // The stored snapshot for a path whose bytes hash to `contentHash`, if this
  // chat already has one. Identical bytes at the same path are one stored copy
  // however many messages cite them; bytes that changed are a new row, which is
  // what makes an overwritten screenshot a second snapshot rather than a silent
  // substitution in the earlier message.
  //
  // Scoped to the chat, not the instance. Every row in this table belongs to
  // exactly one chat, which is what lets `removeForChat` drop rows and bytes by
  // chat id; a row shared between two chats would be deleted out from under the
  // survivor. Two chats showing the same unchanged file therefore keep a copy
  // each, which is the price of being able to delete either one cleanly.
  findAgentImage(
    instanceId: string,
    chatId: string,
    sourcePath: string,
    contentHash: string,
  ): UploadRow | undefined {
    return this.db
      .select()
      .from(schema.uploads)
      .where(
        and(
          eq(schema.uploads.instanceId, instanceId),
          eq(schema.uploads.chatId, chatId),
          eq(schema.uploads.origin, "agent"),
          eq(schema.uploads.sourcePath, sourcePath),
          eq(schema.uploads.contentHash, contentHash),
        ),
      )
      .get();
  }

  // Record a snapshot whose bytes the caller has already written to the host
  // store. Unlike a browser upload there is no staging step: the assistant
  // message that cited the file is known at capture time, so the row is born
  // claimed.
  recordAgentImage(opts: {
    id: string;
    instanceId: string;
    chatId: string;
    messageId: string;
    filename: string;
    mediaType: string;
    size: number;
    sourcePath: string;
    contentHash: string;
  }): Upload {
    this.db
      .insert(schema.uploads)
      .values({ ...opts, origin: "agent" })
      .run();
    return { id: opts.id, filename: opts.filename, mediaType: opts.mediaType, size: opts.size };
  }

  // Associate a snapshot with the message that cited it. Separate from
  // `attach` because that one is the browser's staged-upload claim path, with
  // its own cross-chat rules; here the association is simply a fact.
  attachAgentImage(chatId: string, messageId: string, uploadId: string): void {
    this.db
      .insert(schema.messageUploads)
      .values({ chatId, messageId, uploadId, position: 0 })
      .onConflictDoNothing()
      .run();
  }

  releaseQueuedMessage(chatId: string, messageId: string): void {
    this.db.transaction(() => {
      this.db
        .delete(schema.messageUploads)
        .where(
          and(
            eq(schema.messageUploads.chatId, chatId),
            eq(schema.messageUploads.messageId, messageId),
          ),
        )
        .run();
      this.db
        .update(schema.uploads)
        .set({ chatId: null, messageId: null })
        .where(and(eq(schema.uploads.chatId, chatId), eq(schema.uploads.messageId, messageId)))
        .run();
    });
  }

  // Everything a deleted chat had attached, metadata and bytes alike. The rows
  // have to be read before they are dropped, because their instance and id are
  // what locate the bytes: deleting only the rows would leave the files behind
  // until the whole instance went, which for an agent's inline images is a
  // screenshot per mention rather than the odd hand-picked attachment.
  //
  // Safe to delete the bytes outright because a row belongs to exactly one
  // chat: a browser upload is claimed by the first chat that sends it (see
  // `attach`), and a snapshot is deduped only within its own chat (see
  // `findAgentImage`). A staged upload never sent has no chat and is left for
  // the instance-level sweep.
  removeForChat(chatId: string): void {
    const rows = this.db
      .select({ instanceId: schema.uploads.instanceId, id: schema.uploads.id })
      .from(schema.uploads)
      .where(eq(schema.uploads.chatId, chatId))
      .all();
    this.db.delete(schema.messageUploads).where(eq(schema.messageUploads.chatId, chatId)).run();
    this.db.delete(schema.uploads).where(eq(schema.uploads.chatId, chatId)).run();
    for (const row of rows) {
      try {
        removeUploadDir(row.instanceId, row.id);
      } catch (err) {
        // The row is already gone, so the boot sweep is the backstop. Losing
        // the bytes is not worth failing a delete the user asked for.
        console.warn(`[uploads] failed to remove ${row.id} for deleted chat ${chatId}:`, err);
      }
    }
  }
}

/** Boot sweep: drop upload dirs whose instance no longer exists (a missed
 * removal, or a crash between create and the instance insert). */
export function sweepUploads(liveInstanceIds: ReadonlySet<string>): void {
  const root = join(stateDir(), "uploads");
  let entries: string[];
  try {
    entries = readdirSync(root);
  } catch {
    return; // no uploads dir → nothing to sweep
  }
  for (const entry of entries) {
    if (liveInstanceIds.has(entry)) continue;
    try {
      rmSync(join(root, entry), { recursive: true, force: true });
      console.log(`[uploads] swept orphaned upload dir ${entry}`);
    } catch (err) {
      console.warn(`[uploads] failed to sweep ${entry}:`, err);
    }
  }
}
