import { mkdirSync, readdirSync, rmSync } from "node:fs";
import { basename, join } from "node:path";
import { and, asc, eq, inArray, isNull } from "drizzle-orm";
import type { Upload } from "./contracts";
import type { Db } from "./db";
import { schema } from "./db";
import type { UploadRow } from "./db/schema";
import { stateDir } from "./xdg";

// Message file attachments (browser upload / clipboard paste).
//
// A file is written ONCE at upload time (see the uploads route) to two places,
// both streamed so a large file never sits fully in memory:
//   - the host, under stateDir()/uploads/<instanceId>/<id>/<name>, the source
//     of truth backing the web preview and the user-facing download; and
//   - into the instance's running VM at GUEST_UPLOADS_DIR/<id>/<name>, so the
//     agent can read it by a stable absolute path.
// The VM copy is written by piping the bytes into a shell running AS THE AGENT
// USER (not root), so the files are agent-owned. That also means no bind mount
// (which can't cross the nested-isolade boundary) and no sandbox-service
// change. It lands on the VM's persistent overlay, so it survives restarts.
// There is no per-turn copy.
//
// The DB `uploads` table holds the metadata (see db/schema.ts). This module
// owns only the on-disk layout.

// Guest dir for uploads. Under /var/tmp because it's world-writable (mode 1777)
// so the agent user can create it, AND disk-backed (unlike /tmp, which is a
// tmpfs), so uploads survive VM restarts. Outside /workspace so they never show
// up in git status or the diff stats.
export const GUEST_UPLOADS_DIR = "/var/tmp/isolade/uploads";

/** Per-instance host dir holding the source-of-truth copies. */
export function uploadsInstanceDir(instanceId: string): string {
  return join(stateDir(), "uploads", instanceId);
}

// Keep the original filename (the model benefits from a real name) but strip
// any directory component so a crafted name can't escape the upload's own
// subdir. Fall back to a generic name when nothing usable is left.
export function safeFilename(filename: string): string {
  const base = basename(filename).replace(/^\.+/, "").trim();
  return base.length > 0 ? base : "file";
}

/** Host dir holding one upload's bytes. Created (recursively) so the route can
 * stream the request body straight into `<dir>/<name>`. */
export function ensureHostUploadDir(instanceId: string, id: string): string {
  const dir = join(uploadsInstanceDir(instanceId), id);
  mkdirSync(dir, { recursive: true });
  return dir;
}

/** Host path to a stored upload's bytes (download / preview / delete). */
export function uploadHostPath(instanceId: string, id: string, filename: string): string {
  return join(uploadsInstanceDir(instanceId), id, safeFilename(filename));
}

/** The per-upload dir inside the guest (parent of the bytes). `id` is a uuid,
 * so this is safe to interpolate into a shell command, but the route quotes it
 * anyway. */
export function guestUploadDir(id: string): string {
  return `${GUEST_UPLOADS_DIR}/${id}`;
}

/** Absolute path the agent sees inside the VM. Cited in the outgoing user
 * message so both providers can read it (Claude `Read`, codex `view_image` /
 * shell). Absolute so it's unambiguous across a multi-repo workspace. */
export function uploadGuestPath(id: string, filename: string): string {
  return `${guestUploadDir(id)}/${safeFilename(filename)}`;
}

/** Drop an instance's whole uploads dir when the instance is removed. */
export function removeUploadsForInstance(instanceId: string): void {
  rmSync(uploadsInstanceDir(instanceId), { recursive: true, force: true });
}

/** The wire view of an upload row (drops the internal association columns). */
export function toUpload(row: UploadRow): Upload {
  return { id: row.id, filename: row.filename, mediaType: row.mediaType, size: row.size };
}

// DB-backed store for upload metadata. Filesystem layout lives in the free
// functions above; this owns the `uploads` table.
export class UploadStore {
  constructor(private readonly db: Db) {}

  // Record the metadata row for an upload whose bytes the route has already
  // streamed to disk (and into the VM). messageId is null until the upload is
  // attached to a sent message. `id` and `filename` are the same ones used for
  // the on-disk paths, so they must already be sanitized/generated by the route.
  record(opts: {
    id: string;
    instanceId: string;
    filename: string;
    mediaType: string;
    size: number;
  }): Upload {
    this.db
      .insert(schema.uploads)
      .values({
        id: opts.id,
        instanceId: opts.instanceId,
        chatId: null,
        messageId: null,
        filename: opts.filename,
        mediaType: opts.mediaType,
        size: opts.size,
      })
      .run();
    return { id: opts.id, filename: opts.filename, mediaType: opts.mediaType, size: opts.size };
  }

  get(id: string): UploadRow | undefined {
    return this.db.select().from(schema.uploads).where(eq(schema.uploads.id, id)).get();
  }

  // Associate uploads with a sent message. A staged upload is claimed by this
  // chat on first use. An upload already claimed by the same chat may be reused
  // by an edited message version, while cross-instance and cross-chat ids are
  // ignored. The junction keeps the original message's association intact.
  // Returns the attached rows in caller-provided order.
  attach(instanceId: string, chatId: string, messageId: string, ids: string[]): UploadRow[] {
    const uniqueIds = [...new Set(ids)];
    if (uniqueIds.length === 0) return [];

    const candidates = this.db
      .select()
      .from(schema.uploads)
      .where(and(eq(schema.uploads.instanceId, instanceId), inArray(schema.uploads.id, uniqueIds)))
      .all();
    const allowed = candidates.filter((row) => row.messageId === null || row.chatId === chatId);
    if (allowed.length === 0) return [];
    const allowedIds = allowed.map((row) => row.id);

    // First use claims the upload for this chat. These columns remain the
    // first-claim marker even when later message versions reuse the upload.
    this.db
      .update(schema.uploads)
      .set({ chatId, messageId })
      .where(
        and(
          eq(schema.uploads.instanceId, instanceId),
          inArray(schema.uploads.id, allowedIds),
          isNull(schema.uploads.messageId),
        ),
      )
      .run();

    this.db
      .insert(schema.messageUploads)
      .values(
        uniqueIds
          .filter((id) => allowedIds.includes(id))
          .map((uploadId, position) => ({ chatId, messageId, uploadId, position })),
      )
      .onConflictDoNothing()
      .run();

    const byId = new Map(allowed.map((row) => [row.id, row]));
    return uniqueIds.map((id) => byId.get(id)).filter((row): row is UploadRow => row !== undefined);
  }

  // Uploads for every message of a chat, grouped by messageId, so a transcript
  // fetch can decorate its messages in one query instead of N.
  byMessageForChat(chatId: string): Map<string, Upload[]> {
    const rows = this.db
      .select({ association: schema.messageUploads, upload: schema.uploads })
      .from(schema.messageUploads)
      .innerJoin(schema.uploads, eq(schema.messageUploads.uploadId, schema.uploads.id))
      .where(eq(schema.messageUploads.chatId, chatId))
      .orderBy(asc(schema.messageUploads.position))
      .all();
    const map = new Map<string, Upload[]>();
    for (const { association, upload } of rows) {
      const list = map.get(association.messageId) ?? [];
      list.push(toUpload(upload));
      map.set(association.messageId, list);
    }
    return map;
  }

  listForMessage(messageId: string): Upload[] {
    return this.db
      .select({ upload: schema.uploads })
      .from(schema.messageUploads)
      .innerJoin(schema.uploads, eq(schema.messageUploads.uploadId, schema.uploads.id))
      .where(eq(schema.messageUploads.messageId, messageId))
      .orderBy(asc(schema.messageUploads.position))
      .all()
      .map(({ upload }) => toUpload(upload));
  }

  removeForChat(chatId: string): void {
    this.db.delete(schema.messageUploads).where(eq(schema.messageUploads.chatId, chatId)).run();
    this.db.delete(schema.uploads).where(eq(schema.uploads.chatId, chatId)).run();
  }
}

/** Boot sweep: drop upload dirs whose instance no longer exists (a missed
 * removal, or a crash between create and the instance insert). */
export function sweepUploads(liveInstanceIds: ReadonlySet<string>): void {
  const root = join(stateDir(), "uploads");
  let entries: string[];
  try {
    entries = readdirSync(root);
  } catch {
    return; // no uploads dir → nothing to sweep
  }
  for (const entry of entries) {
    if (liveInstanceIds.has(entry)) continue;
    try {
      rmSync(join(root, entry), { recursive: true, force: true });
      console.log(`[uploads] swept orphaned upload dir ${entry}`);
    } catch (err) {
      console.warn(`[uploads] failed to sweep ${entry}:`, err);
    }
  }
}
